# Generated by Django 3.2.6 on 2022-06-01 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import times.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batalha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winer_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChampionChip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lock', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('start', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(unique=True, upload_to=times.models.game_image)),
            ],
        ),
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to=times.models.upload_Organization)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=255)),
                ('birth', models.DateTimeField()),
                ('ranking', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ranking', models.IntegerField(default=0)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietario', to='times.player')),
                ('players', models.ManyToManyField(to='times.Player')),
            ],
            options={
                'ordering': ['-ranking', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lvl', models.IntegerField()),
                ('img', models.ImageField(unique=True, upload_to=times.models.rank_image)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='times.game')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerConvit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ingrece', models.BooleanField(default=False)),
                ('send', models.DateTimeField(auto_now_add=True)),
                ('acept', models.DateTimeField()),
                ('to_player', models.BooleanField(default=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.player')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.time')),
            ],
        ),
        migrations.CreateModel(
            name='Inscrisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championchip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_game', to='times.championchip')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.player')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.time')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='categors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.gamecategory'),
        ),
        migrations.AddField(
            model_name='championchip',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='championchip', to='times.game'),
        ),
        migrations.AddField(
            model_name='championchip',
            name='games',
            field=models.ManyToManyField(blank=True, to='times.Batalha'),
        ),
        migrations.AddField(
            model_name='championchip',
            name='organiz',
            field=models.ManyToManyField(blank=True, null=True, to='times.Organization'),
        ),
        migrations.AddField(
            model_name='batalha',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_read', to='times.time'),
        ),
        migrations.AddField(
            model_name='batalha',
            name='player2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_blue', to='times.time'),
        ),
    ]
