# Generated by Django 3.2.6 on 2022-06-01 21:04

from django.db import migrations, models
import django.db.models.deletion
import times.models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0002_alter_championchip_organiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='championchip',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=times.models.championchip_banner),
        ),
        migrations.AlterField(
            model_name='inscrisao',
            name='time',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='times.time'),
        ),
    ]
