# Generated by Django 3.2.6 on 2022-06-04 17:52

from django.db import migrations, models
import times.models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0003_auto_20220601_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championchip',
            name='banner',
            field=models.ImageField(null=True, upload_to=times.models.championchip_banner),
        ),
    ]
