# Generated by Django 3.2.6 on 2022-06-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0004_alter_championchip_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rank',
            options={'ordering': ['-game', '-lvl', '-pk']},
        ),
        migrations.RemoveField(
            model_name='player',
            name='ranking',
        ),
        migrations.AddField(
            model_name='player',
            name='ranking',
            field=models.ManyToManyField(related_name='players_count', to='times.Rank'),
        ),
    ]
