# Generated by Django 3.2.6 on 2022-06-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0005_auto_20220604_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerconvit',
            name='kick',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playerconvit',
            name='acept',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
