# Generated by Django 3.2.6 on 2022-07-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0007_auto_20220701_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='players',
            field=models.ManyToManyField(related_name='times', to='times.Player'),
        ),
    ]
