# Generated by Django 3.2.6 on 2022-07-07 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0008_alter_time_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerconvit',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscrisoes', to='times.time'),
        ),
    ]
